version: '2.2'
services:
  unifi:
    image: "goofball222/unifi:latest"
    init: true
    ports:
     - "3478:3478/udp"
     - "6789:6789"
     - "8080:8080"
     - "8443:8443"
     - "8880:8880"
     - "8843:8843"
     - "10001:10001/udp"
    volumes:
     - /path/to/unifi/certs:/usr/lib/unifi/cert
     - /path/to/unifi/data:/usr/lib/unifi/data
     - /path/to/unifi/logs:/usr/lib/unifi/logs
